kind: Namespace
apiVersion: v1
metadata:
  name: chartlab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chartlab-deployment
  namespace: chartlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chartlab-deployment
  template:
    metadata:
      labels:
        app: chartlab-deployment
    spec:
      containers:
      - name: chartlab-app
        image: aidendeloryn/chartlab:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        - containerPort: 443
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/os
                  operator: NotIn
                  values:
                  - windows
---
apiVersion: v1
kind: Service
metadata:
  name: chartlab-service
  namespace: chartlab
spec:
  selector:
    app: chartlab-deployment
  type: NodePort
  ports:
  - name: http
    port: 80
  - name: https
    port: 443